/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src.internalPAge;

import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author COLLEGE17
 */
public class dashboardPage extends javax.swing.JInternalFrame {

    /**
     * Creates new form dashboardPage
     */
    public dashboardPage() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi =(BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }
    Color navcolor = new Color(0,102,153);
    Color headercolor = new Color(0,153,204);
    Color bodycolor = new Color(153,204,255);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        studentinfo = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        log = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        updatelog1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(570, 380));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\COLLEGE17\\Downloads\\icons8-name-100.png")); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 90, 90));

        jPanel1.add(jPanel3);
        jPanel3.setBounds(400, 0, 100, 120);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("MAMB0 LIBRARY LOGGER   V1.1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 0, 320, 50);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 100));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setLayout(null);

        studentinfo.setBackground(new java.awt.Color(0, 153, 204));
        studentinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentinfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studentinfoMouseExited(evt);
            }
        });
        studentinfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\COLLEGE17\\Downloads\\icons8-identification-documents-100.png")); // NOI18N
        studentinfo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("  Input Student Info");
        studentinfo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 110, -1, -1));

        jPanel2.add(studentinfo);
        studentinfo.setBounds(30, 70, 140, 150);

        log.setBackground(new java.awt.Color(0, 153, 204));
        log.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updatelogMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updatelogMouseExited(evt);
            }
        });
        log.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\COLLEGE17\\Downloads\\icons8-log-80.png")); // NOI18N
        log.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 90));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Daily Logs");
        log.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jPanel2.add(log);
        log.setBounds(210, 70, 150, 150);

        updatelog1.setBackground(new java.awt.Color(0, 153, 204));
        updatelog1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updatelog1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updatelog1MouseExited(evt);
            }
        });
        updatelog1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\COLLEGE17\\Downloads\\icons8-update-100.png")); // NOI18N
        updatelog1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Update Logs");
        updatelog1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jPanel2.add(updatelog1);
        updatelog1.setBounds(400, 70, 140, 150);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 600, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentinfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentinfoMouseEntered
       studentinfo.setBackground(navcolor);
    }//GEN-LAST:event_studentinfoMouseEntered

    private void studentinfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentinfoMouseExited
        studentinfo.setBackground(headercolor);
    }//GEN-LAST:event_studentinfoMouseExited

    private void updatelogMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatelogMouseEntered
        log.setBackground(navcolor);
    }//GEN-LAST:event_updatelogMouseEntered

    private void updatelogMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatelogMouseExited
        log.setBackground(headercolor);
    }//GEN-LAST:event_updatelogMouseExited

    private void updatelog1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatelog1MouseEntered
        updatelog1.setBackground(navcolor);
    }//GEN-LAST:event_updatelog1MouseEntered

    private void updatelog1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatelog1MouseExited
        updatelog1.setBackground(headercolor);
    }//GEN-LAST:event_updatelog1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel log;
    private javax.swing.JPanel studentinfo;
    private javax.swing.JPanel updatelog1;
    // End of variables declaration//GEN-END:variables
}
